# Generated by Django 4.2.1 on 2023-05-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_doctor_data_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='')),
                ('blog_subTitle', models.CharField(max_length=100)),
                ('blog_description', models.TextField()),
                ('publish_day', models.CharField(max_length=50)),
                ('publish_time', models.TimeField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
