# Generated by Django 4.2.1 on 2023-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blog_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_data',
            name='doctor_clinic_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor_data',
            name='doctor_description_of_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_list',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
