# Generated by Django 4.1.7 on 2023-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_doctor_data_doctor_clinic_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=400)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_list',
        ),
        migrations.DeleteModel(
            name='doctor_Data',
        ),
    ]
