# Generated by Django 4.1.7 on 2023-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_client_data_message_alter_client_data_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('linkin', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('instgram', models.CharField(max_length=200)),
            ],
        ),
    ]
