# Generated by Django 4.1.7 on 2023-06-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='services',
        ),
    ]
